### ISSUE TITLE
Readme guide missing a step

### ISSUE THREAD

**Issue by AJAnderson** [jplatte/cargo-depgraph#13]
Hello,

The installation and first use guide is a bit hard to understand, I'm currently stuck as I don't know what "dot" is that the output of depgraph is being piped to, it's not a super easy thing to google either. It's not a recognized internal command on windows, so perhaps a brief explanation on what this is would help new users like myself?

**Comment by AJAnderson** [comment]
Figured out it's the shorthand for a tool graphviz offers. Minor papercut for new users not starting with graphviz installed or otherwise knowing all that much about it.

**Comment by jplatte** [comment]
Added a note in ba86465c46707a3c2d4f5912fc0eba63b20a2c61. Let me know if you think it still needs further improvements.

**Comment by AJAnderson** [comment]
Yeah that looks great, thank you!
