### ISSUE TITLE
Add --depth argument

### ISSUE THREAD

**Issue by AlexandreCassagne** [jplatte/cargo-depgraph#18]
Allow users to specify the depth of dependencies to render.

See also `--direct-dependencies-only` 

See [this commit page](https://github.com/jplatte/cargo-depgraph/commit/38a05fe852f5c2923b06a268815fb12737c8108e) for discussion.

**Comment by BennD** [comment]
Are you interested in tackling this? Otherwise i might try to implement this when i'm back from work.

**Comment by jplatte** [comment]
Done in #19, I'll release it soon.

**Comment by AlexandreCassagne** [comment]
Thanks for taking care of it! A little too busy at the moment :)

**Comment by jplatte** [comment]
Release as v1.6.0!
